export const LANGUAGE_CONFIG = {
  javascript: {
    id: "javascript",
    label: "JavaScript",
    logoPath: "/javascript.png",
    pistonRuntime: { language: "javascript", version: "18.15.0" },
    monacoLanguage: "javascript",
    defaultCode: "// Write your JavaScript code here\nconst greeting = \"Hello World\";\nconsole.log(greeting);",
  },
  typescript: {
    id: "typescript",
    label: "TypeScript",
    logoPath: "/typescript.png",
    pistonRuntime: { language: "typescript", version: "5.0.3" },
    monacoLanguage: "typescript",
    defaultCode: "// Write your TypeScript code here\nlet message: string = \"Hello TypeScript\";\nconsole.log(message);",
  },
  python: {
    id: "python",
    label: "Python",
    logoPath: "/python.png",
    pistonRuntime: { language: "python", version: "3.10.0" },
    monacoLanguage: "python",
    defaultCode: "# Write your Python code here\ngreeting = \"Hello Python\"\nprint(greeting)",
  },
  java: {
    id: "java",
    label: "Java",
    logoPath: "/java.png",
    pistonRuntime: { language: "java", version: "15.0.2" },
    monacoLanguage: "java",
    defaultCode: "// Write your Java code here\npublic class Main {\n  public static void main(String[] args) {\n    String greeting = \"Hello Java\";\n    System.out.println(greeting);\n  }\n}",
  },
  go: {
    id: "go",
    label: "Go",
    logoPath: "/go.png",
    pistonRuntime: { language: "go", version: "1.16.2" },
    monacoLanguage: "go",
    defaultCode: "// Write your Go code here\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n  greeting := \"Hello Go\"\n  fmt.Println(greeting)\n}",
  },
  rust: {
    id: "rust",
    label: "Rust",
    logoPath: "/rust.png",
    pistonRuntime: { language: "rust", version: "1.68.2" },
    monacoLanguage: "rust",
    defaultCode: "// Write your Rust code here\nfn main() {\n  let greeting = \"Hello Rust\";\n  println!(\"{}\", greeting);\n}",
  },
  cpp: {
    id: "cpp",
    label: "C++",
    logoPath: "/cpp.png",
    pistonRuntime: { language: "cpp", version: "10.2.0" },
    monacoLanguage: "cpp",
    defaultCode: "// Write your C++ code here\n#include <iostream>\n\nusing namespace std;\n\nint main() {\n  string greeting = \"Hello C++\";\n  cout << greeting << endl;\n  return 0;\n}",
  },
  csharp: {
    id: "csharp",
    label: "C#",
    logoPath: "/csharp.png",
    pistonRuntime: { language: "csharp", version: "6.12.0" },
    monacoLanguage: "csharp",
    defaultCode: "// Write your C# code here\nusing System;\n\nclass Program {\n  static void Main() {\n    string greeting = \"Hello C#\";\n    Console.WriteLine(greeting);\n  }\n}",
  },
  ruby: {
    id: "ruby",
    label: "Ruby",
    logoPath: "/ruby.png",
    pistonRuntime: { language: "ruby", version: "3.0.1" },
    monacoLanguage: "ruby",
    defaultCode: "# Write your Ruby code here\ngreeting = \"Hello Ruby\"\nputs greeting",
  },
  swift: {
    id: "swift",
    label: "Swift",
    logoPath: "/swift.png",
    pistonRuntime: { language: "swift", version: "5.3.3" },
    monacoLanguage: "swift",
    defaultCode: "// Write your Swift code here\nlet greeting = \"Hello Swift\"\nprint(greeting)",
  },
};

export default LANGUAGE_CONFIG;

// Define the available themes
export const THEMES = [
  { id: "vs-dark", label: "VS Dark", color: "#1e1e1e" },
  { id: "vs-light", label: "VS Light", color: "#ffffff" },
  { id: "github-dark", label: "GitHub Dark", color: "#0d1117" },
  { id: "monokai", label: "Monokai", color: "#272822" },
  { id: "solarized-dark", label: "Solarized Dark", color: "#002b36" },
];

// Theme definitions
export const THEME_DEFINITIONS = {
  "github-dark": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6e7681" },
      { token: "string", foreground: "a5d6ff" },
      { token: "keyword", foreground: "ff7b72" },
      { token: "number", foreground: "79c0ff" },
      { token: "type", foreground: "ffa657" },
      { token: "class", foreground: "ffa657" },
      { token: "function", foreground: "d2a8ff" },
      { token: "variable", foreground: "c9d1d9" },
      { token: "operator", foreground: "ff7b72" },
      { token: "constant", foreground: "79c0ff" },
      { token: "property", foreground: "79c0ff" },
      { token: "parameter", foreground: "ffa657" },
      { token: "punctuation", foreground: "c9d1d9" },
      { token: "tag", foreground: "7ee787" },
      { token: "attribute.name", foreground: "d2a8ff" },
      { token: "attribute.value", foreground: "a5d6ff" },
      { token: "delimiter", foreground: "c9d1d9" },
      { token: "delimiter.angle", foreground: "c9d1d9" },
      { token: "delimiter.curly", foreground: "c9d1d9" },
      { token: "delimiter.square", foreground: "c9d1d9" },
      { token: "delimiter.parenthesis", foreground: "c9d1d9" },
      { token: "meta", foreground: "c9d1d9" },
      { token: "meta.tag", foreground: "7ee787" },
      { token: "metatag", foreground: "7ee787" },
      { token: "namespace", foreground: "ffa657" },
      { token: "entity.name.namespace", foreground: "ffa657" },
      { token: "predefined", foreground: "79c0ff" },
      { token: "predefined.sql", foreground: "79c0ff" },
      { token: "type.identifier", foreground: "ffa657" },
      { token: "constructor", foreground: "d2a8ff" },
      { token: "modifier", foreground: "ff7b72" },
      { token: "identifier", foreground: "c9d1d9" },
      { token: "entity.name.function", foreground: "d2a8ff" },
      { token: "entity.name.class", foreground: "ffa657" },
      { token: "entity.name.tag", foreground: "7ee787" },
      { token: "keyword.control", foreground: "ff7b72" },
      { token: "keyword.operator", foreground: "ff7b72" },
      { token: "keyword.preprocessor", foreground: "ff7b72" },
      { token: "storage.type", foreground: "ff7b72" },
      { token: "storage.modifier", foreground: "ff7b72" },
      { token: "support.function", foreground: "79c0ff" },
      { token: "support.method", foreground: "79c0ff" },
      { token: "support.class", foreground: "79c0ff" },
      { token: "support.type", foreground: "ffa657" },
      { token: "variable.language", foreground: "ff7b72" },
      { token: "variable.other", foreground: "c9d1d9" },
      { token: "variable.parameter", foreground: "ffa657" },
      { token: "method", foreground: "d2a8ff" },
    ],
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#c9d1d9",
      "editor.lineHighlightBackground": "#161b22",
      "editorLineNumber.foreground": "#6e7681",
      "editorIndentGuide.background": "#21262d",
      "editor.selectionBackground": "#264f78",
      "editor.inactiveSelectionBackground": "#264f7855",
    },
  },
  monokai: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "75715E" },
      { token: "string", foreground: "E6DB74" },
      { token: "keyword", foreground: "F92672" },
      { token: "number", foreground: "AE81FF" },
      { token: "type", foreground: "66D9EF", fontStyle: "italic" },
      { token: "class", foreground: "A6E22E" },
      { token: "function", foreground: "A6E22E" },
      { token: "variable", foreground: "F8F8F2" },
      { token: "operator", foreground: "F92672" },
      { token: "constant", foreground: "AE81FF" },
      { token: "property", foreground: "66D9EF" },
      { token: "parameter", foreground: "FD971F" },
      { token: "punctuation", foreground: "F8F8F2" },
      { token: "tag", foreground: "F92672" },
      { token: "attribute.name", foreground: "A6E22E" },
      { token: "attribute.value", foreground: "E6DB74" },
      { token: "delimiter", foreground: "F8F8F2" },
      { token: "delimiter.angle", foreground: "F8F8F2" },
      { token: "delimiter.curly", foreground: "F92672" },
      { token: "delimiter.square", foreground: "F8F8F2" },
      { token: "delimiter.parenthesis", foreground: "F8F8F2" },
      { token: "meta", foreground: "F8F8F2" },
      { token: "meta.tag", foreground: "F92672" },
      { token: "metatag", foreground: "F92672" },
      { token: "namespace", foreground: "A6E22E" },
      { token: "entity.name.namespace", foreground: "A6E22E" },
      { token: "predefined", foreground: "66D9EF" },
      { token: "predefined.sql", foreground: "66D9EF" },
      { token: "type.identifier", foreground: "66D9EF" },
      { token: "constructor", foreground: "A6E22E" },
      { token: "modifier", foreground: "F92672" },
      { token: "identifier", foreground: "F8F8F2" },
      { token: "entity.name.function", foreground: "A6E22E" },
      { token: "entity.name.class", foreground: "A6E22E" },
      { token: "entity.name.tag", foreground: "F92672" },
      { token: "keyword.control", foreground: "F92672" },
      { token: "keyword.operator", foreground: "F92672" },
      { token: "keyword.preprocessor", foreground: "F92672" },
      { token: "storage.type", foreground: "66D9EF", fontStyle: "italic" },
      { token: "storage.modifier", foreground: "F92672" },
      { token: "support.function", foreground: "66D9EF" },
      { token: "support.method", foreground: "66D9EF" },
      { token: "support.class", foreground: "66D9EF", fontStyle: "italic" },
      { token: "support.type", foreground: "66D9EF", fontStyle: "italic" },
      { token: "variable.language", foreground: "FD971F" },
      { token: "variable.other", foreground: "F8F8F2" },
      { token: "variable.parameter", foreground: "FD971F" },
      { token: "method", foreground: "A6E22E" },
    ],
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#F8F8F2",
      "editorLineNumber.foreground": "#75715E",
      "editor.selectionBackground": "#49483E",
      "editor.lineHighlightBackground": "#3E3D32",
      "editorCursor.foreground": "#F8F8F2",
      "editor.selectionHighlightBackground": "#49483E",
    },
  },
  "solarized-dark": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "586e75" },
      { token: "string", foreground: "2aa198" },
      { token: "keyword", foreground: "859900" },
      { token: "number", foreground: "d33682" },
      { token: "type", foreground: "b58900" },
      { token: "class", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
      { token: "variable", foreground: "b58900" },
      { token: "operator", foreground: "859900" },
      { token: "constant", foreground: "d33682" },
      { token: "property", foreground: "268bd2" },
      { token: "parameter", foreground: "cb4b16" },
      { token: "punctuation", foreground: "839496" },
      { token: "tag", foreground: "268bd2" },
      { token: "attribute.name", foreground: "93a1a1" },
      { token: "attribute.value", foreground: "2aa198" },
      { token: "delimiter", foreground: "839496" },
      { token: "delimiter.angle", foreground: "839496" },
      { token: "delimiter.curly", foreground: "839496" },
      { token: "delimiter.square", foreground: "839496" },
      { token: "delimiter.parenthesis", foreground: "839496" },
      { token: "meta", foreground: "839496" },
      { token: "meta.tag", foreground: "268bd2" },
      { token: "metatag", foreground: "268bd2" },
      { token: "namespace", foreground: "b58900" },
      { token: "entity.name.namespace", foreground: "b58900" },
      { token: "predefined", foreground: "cb4b16" },
      { token: "predefined.sql", foreground: "cb4b16" },
      { token: "type.identifier", foreground: "b58900" },
      { token: "constructor", foreground: "268bd2" },
      { token: "modifier", foreground: "859900" },
      { token: "identifier", foreground: "839496" },
      { token: "entity.name.function", foreground: "268bd2" },
      { token: "entity.name.class", foreground: "b58900" },
      { token: "entity.name.tag", foreground: "268bd2" },
      { token: "keyword.control", foreground: "859900" },
      { token: "keyword.operator", foreground: "859900" },
      { token: "keyword.preprocessor", foreground: "cb4b16" },
      { token: "storage.type", foreground: "859900" },
      { token: "storage.modifier", foreground: "859900" },
      { token: "support.function", foreground: "268bd2" },
      { token: "support.class", foreground: "b58900" },
      { token: "support.type", foreground: "b58900" },
      { token: "variable.language", foreground: "cb4b16" },
      { token: "variable.other", foreground: "839496" },
      { token: "variable.parameter", foreground: "cb4b16" },
    ],
    colors: {
      "editor.background": "#002b36",
      "editor.foreground": "#839496",
      "editorLineNumber.foreground": "#586e75",
      "editor.selectionBackground": "#073642",
      "editor.lineHighlightBackground": "#073642",
      "editorCursor.foreground": "#839496",
      "editor.selectionHighlightBackground": "#073642",
    },
  },
  "vs-light": {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "008000" },
      { token: "string", foreground: "a31515" },
      { token: "keyword", foreground: "0000ff" },
      { token: "number", foreground: "098658" },
      { token: "type", foreground: "267f99" },
      { token: "class", foreground: "267f99" },
      { token: "function", foreground: "795e26" },
      { token: "variable", foreground: "001080" },
      { token: "operator", foreground: "0000ff" },
      { token: "constant", foreground: "0070c1" },
      { token: "property", foreground: "001080" },
      { token: "parameter", foreground: "001080" },
      { token: "punctuation", foreground: "000000" },
      { token: "tag", foreground: "800000" },
      { token: "attribute.name", foreground: "ff0000" },
      { token: "attribute.value", foreground: "0000ff" },
      { token: "delimiter", foreground: "000000" },
      { token: "delimiter.angle", foreground: "0000ff" },
      { token: "delimiter.curly", foreground: "000000" },
      { token: "delimiter.square", foreground: "000000" },
      { token: "delimiter.parenthesis", foreground: "000000" },
      { token: "meta", foreground: "000000" },
      { token: "meta.tag", foreground: "800000" },
      { token: "metatag", foreground: "800000" },
      { token: "namespace", foreground: "267f99" },
      { token: "entity.name.namespace", foreground: "267f99" },
      { token: "predefined", foreground: "0070c1" },
      { token: "predefined.sql", foreground: "0070c1" },
      { token: "type.identifier", foreground: "267f99" },
      { token: "constructor", foreground: "795e26" },
      { token: "modifier", foreground: "0000ff" },
      { token: "identifier", foreground: "001080" },
      { token: "entity.name.function", foreground: "795e26" },
      { token: "entity.name.class", foreground: "267f99" },
      { token: "entity.name.tag", foreground: "800000" },
      { token: "keyword.control", foreground: "0000ff" },
      { token: "keyword.operator", foreground: "0000ff" },
      { token: "keyword.preprocessor", foreground: "0000ff" },
      { token: "storage.type", foreground: "0000ff" },
      { token: "storage.modifier", foreground: "0000ff" },
      { token: "support.function", foreground: "795e26" },
      { token: "support.class", foreground: "267f99" },
      { token: "support.type", foreground: "267f99" },
      { token: "variable.language", foreground: "0070c1" },
      { token: "variable.other", foreground: "001080" },
      { token: "variable.parameter", foreground: "001080" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#000000",
      "editorLineNumber.foreground": "#237893",
      "editor.selectionBackground": "#add6ff",
      "editor.lineHighlightBackground": "#f3f3f3",
      "editorCursor.foreground": "#000000",
    },
  },
  "vs-dark": {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6A9955" },
      { token: "string", foreground: "ce9178" },
      { token: "keyword", foreground: "569cd6" },
      { token: "number", foreground: "b5cea8" },
      { token: "type", foreground: "4ec9b0" },
      { token: "class", foreground: "4ec9b0" },
      { token: "function", foreground: "dcdcaa" },
      { token: "variable", foreground: "9cdcfe" },
      { token: "operator", foreground: "d4d4d4" },
      { token: "constant", foreground: "4fc1ff" },
      { token: "property", foreground: "9cdcfe" },
      { token: "parameter", foreground: "9cdcfe" },
      { token: "punctuation", foreground: "d4d4d4" },
      { token: "tag", foreground: "569cd6" },
      { token: "attribute.name", foreground: "9cdcfe" },
      { token: "attribute.value", foreground: "ce9178" },
      { token: "delimiter", foreground: "d4d4d4" },
      { token: "delimiter.angle", foreground: "d4d4d4" },
      { token: "delimiter.curly", foreground: "d4d4d4" },
      { token: "delimiter.square", foreground: "d4d4d4" },
      { token: "delimiter.parenthesis", foreground: "d4d4d4" },
      { token: "meta", foreground: "d4d4d4" },
      { token: "meta.tag", foreground: "569cd6" },
      { token: "metatag", foreground: "569cd6" },
      { token: "namespace", foreground: "4ec9b0" },
      { token: "entity.name.namespace", foreground: "4ec9b0" },
      { token: "predefined", foreground: "4fc1ff" },
      { token: "predefined.sql", foreground: "4fc1ff" },
      { token: "type.identifier", foreground: "4ec9b0" },
      { token: "constructor", foreground: "dcdcaa" },
      { token: "modifier", foreground: "569cd6" },
      { token: "identifier", foreground: "9cdcfe" },
      { token: "entity.name.function", foreground: "dcdcaa" },
      { token: "entity.name.class", foreground: "4ec9b0" },
      { token: "entity.name.tag", foreground: "569cd6" },
      { token: "keyword.control", foreground: "569cd6" },
      { token: "keyword.operator", foreground: "d4d4d4" },
      { token: "keyword.preprocessor", foreground: "569cd6" },
      { token: "storage.type", foreground: "569cd6" },
      { token: "storage.modifier", foreground: "569cd6" },
      { token: "support.function", foreground: "dcdcaa" },
      { token: "support.class", foreground: "4ec9b0" },
      { token: "support.type", foreground: "4ec9b0" },
      { token: "variable.language", foreground: "569cd6" },
      { token: "variable.other", foreground: "9cdcfe" },
      { token: "variable.parameter", foreground: "9cdcfe" },
    ],
    colors: {
      "editor.background": "#1e1e1e",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#858585",
      "editor.selectionBackground": "#264f78",
      "editor.lineHighlightBackground": "#2a2d2e",
      "editorCursor.foreground": "#d4d4d4",
      "editor.selectionHighlightBackground": "#2a3d56",
    },
  },
};

// Helper function to define themes in Monaco
export const defineMonacoThemes = (monaco) => {
  // Define all themes with complete token rules
  Object.entries(THEME_DEFINITIONS).forEach(([themeName, themeData]) => {
    monaco.editor.defineTheme(themeName, {
      base: themeData.base,
      inherit: themeData.inherit,
      rules: themeData.rules.map((rule) => ({
        ...rule,
        foreground: rule.foreground,
        fontStyle: rule.fontStyle || '',
      })),
      colors: themeData.colors,
    });
  });
};